modLoader="javafml"
loaderVersion="[43,)"
license="code is MIT, art is CC-BY-NC"

[[mods]]
modId="omlib"
version="${file.jarVersion}"
displayName="OMLib"
authors="Keridos, jmlovelace, leinierperez"
description='''
This is OMLib, the Library for all OpenModular mods
'''

[[dependencies.omlib]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.omlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
